const AuditEventType = Object.freeze({
  TRANSACTION_CREATED: 'TRANSACTION_CREATED',
  PAYMENT_PROCESSED: 'PAYMENT_PROCESSED',
  LEDGER_UPDATED: 'LEDGER_UPDATED',
  POLICY_EVALUATED: 'POLICY_EVALUATED',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
  SYSTEM_EVENT: 'SYSTEM_EVENT',
});

const AuditSeverity = Object.freeze({
  INFO: 'INFO',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
});

const AuditFlag = Object.freeze({
  POLICY_REVIEW: 'POLICY_REVIEW',
  POLICY_BLOCKED: 'POLICY_BLOCKED',
  LIMIT_BREACH: 'LIMIT_BREACH',
  CATEGORY_RESTRICTED: 'CATEGORY_RESTRICTED',
  HIGH_RISK: 'HIGH_RISK',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
});

const AuditOrigin = Object.freeze({
  ENTERPRISE_OVERLAY: 'ENTERPRISE_OVERLAY',
  POLICY_ENGINE: 'POLICY_ENGINE',
  CONTEXT_LAYER: 'CONTEXT_LAYER',
  AUDIT_ENGINE: 'AUDIT_ENGINE',
});

module.exports = {
  AuditEventType,
  AuditSeverity,
  AuditFlag,
  AuditOrigin,
};
