module.exports = {
  USER_CREATED: 'USER_CREATED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  TRANSFER_CREATED: 'TRANSFER_CREATED',
  TRANSFER_COMPLETED: 'TRANSFER_COMPLETED',
  DEPOSIT_CREATED: 'DEPOSIT_CREATED',
  DEPOSIT_COMPLETED: 'DEPOSIT_COMPLETED',
  PIN_FAILED: 'PIN_FAILED',
  PIN_SET: 'PIN_SET',
  PIN_VERIFIED: 'PIN_VERIFIED',
  FRAUD_ALERT: 'FRAUD_ALERT',
  ADMIN_ACTION: 'ADMIN_ACTION'
};
